export const ROUTES = {
  login: 'login',
  buy: 'buy',
  wanted: 'wanted',
  saleListings: 'my-account/my-current-sales-listings',
  wantedListings: 'my-account/my-current-wanted-listings',
  sites: 'my-sites',
  sell: 'sell',
  admin: 'admin',
  haulier: 'haulier-dashboard',
  settings: 'settings',
  logout: 'logout',
  myOffersSelling: 'my-account/my-offers-selling',
  myOffersBuying: 'my-account/my-offers-buying',
  myOffersBuyingDetail: 'my-account/my-buying-offers-details',
  offerDetail: 'offer-detail',
  listingOfferDetail: 'wt_waste_listing',
  liveActiveTable: 'live-activity',
  commercialManagement: 'commercial-management',
  auditTrail: 'audit-trail',
  adminSaleListingDetail: 'admin/listing',
  adminWantedListingDetail: 'admin/wanted-listing',
  adminBuyerActivityDetail: 'admin/buyer-activity',
  adminMemberDetail: 'admin/member',
  landingPage: 'landing-page',
};

export const ROUTES_WITH_SLASH = {
  login: '/login',
  buy: '/buy',
  wanted: '/wanted',
  saleListings: '/my-account/my-current-sales-listings',
  wantedListings: '/my-account/my-current-wanted-listings',
  sites: '/my-sites',
  sell: '/sell',
  admin: '/admin',
  haulier: '/haulier-dashboard',
  settings: '/settings',
  logout: '/logout',
  myOffersSelling: '/my-account/my-offers-selling',
  myOffersBuying: '/my-account/my-offers-buying',
  myOffersBuyingDetail: '/my-account/my-buying-offers-details',
  offerDetail: '/offer-detail',
  listingOfferDetail: '/wt_waste_listing',
  liveActiveTable: '/live-activity',
  commercialManagement: '/commercial-management',
  auditTrail: '/audit-trail',

  adminSaleListingDetail: '/admin/listing',
  adminBuyerActivityDetail: '/admin/buyer-activity',
  adminWantedListingDetail: '/admin/wanted-listing',
  adminMemberDetail: '/admin/member',

  landingPage: '/landing-page',
};
