export const ROUTES = {
  login: 'login',
  buy: 'buy',
  wanted: 'wanted',
  saleListings: 'my-account/my-current-listings',
  sell: 'sell',
  admin: 'admin',
  haulier: 'haulier-dashboard',
  settings: 'settings',
  logout: 'logout',
  myOffersSelling: 'my-account/my-offers-selling',
  myOffersBuying: 'my-account/my-offers-buying',
  myOffersBuyingDetail: 'my-account/my-buying-offers-details',
  offerDetail: 'offer-detail',
  listingOfferDetail: 'wt_waste_listing',
  liveActiveTable: 'live-activity',
  commercialManagement: 'commercial-management',
  adminSaleListingDetail: 'admin/listing',
  adminWantedListingDetail: 'admin/wanted-listing',
};

export const ROUTES_WITH_SLASH = {
  login: '/login',
  buy: '/buy',
  wanted: '/wanted',
  saleListings: '/my-account/my-current-listings',
  sell: '/sell',
  admin: '/admin',
  haulier: '/haulier-dashboard',
  settings: '/settings',
  logout: '/logout',
  myOffersSelling: '/my-account/my-offers-selling',
  myOffersBuying: '/my-account/my-offers-buying',
  myOffersBuyingDetail: '/my-account/my-buying-offers-details',
  offerDetail: '/offer-detail',
  listingOfferDetail: '/wt_waste_listing',
  liveActiveTable: '/live-activity',
  commercialManagement: '/commercial-management',
  adminSaleListingDetail: '/admin/listing',
};
