export const ROUTES = {
  login: 'login',
  buy: 'buy',
  wanted: 'wanted',
  saleListings: 'my-account/my-current-listings',
  sell: 'sell',
  admin: 'admin',
  haulier: 'haulier-dashboard',
  settings: 'settings',
  logout: 'logout',
  myOffers: 'my-offer',
  offerDetail: 'offer-detail',
  listingOfferDetail: 'wt_waste_listing',
  liveActiveTable: 'live-activity',
  commercialManagement: 'commercial-management',
};

export const ROUTES_WITH_SLASH = {
  login: '/login',
  buy: '/buy',
  wanted: '/wanted',
  saleListings: '/my-account/my-current-listings',
  sell: '/sell',
  admin: '/admin',
  haulier: '/haulier-dashboard',
  settings: '/settings',
  logout: '/logout',
  myOffers: '/my-offer',
  offerDetail: '/offer-detail',
  listingOfferDetail: '/wt_waste_listing',
  liveActiveTable: '/live-activity',
  commercialManagement: '/commercial-management',
};
