import { Component, input } from '@angular/core';
import { MatAccordion, MatExpansionModule } from '@angular/material/expansion';
import { MatIconModule } from '@angular/material/icon';
import { mapCountryCodeToName } from '@app/statics';
import { CompanyLocationDetail } from 'app/models';
import { getLocationAddress } from 'app/share/utils/offer';

@Component({
  selector: 'app-admin-member-location',
  imports: [MatAccordion, MatExpansionModule, MatIconModule],
  templateUrl: './admin-member-location.component.html',
  styleUrl: './admin-member-location.component.scss',
})
export class AdminMemberLocationComponent {
  locations = input<CompanyLocationDetail[]>([
    {
      id: 1,
      locationName: 'Main Warehouse',
      prefix: 'dr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '123 Green St, Unit 1',
      street: 'street',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'UG',
      stateProvince: 'England',
      officeOpenTime: '02:00:00',
      officeCloseTime: '12:00:00',
      loadingRamp: false,
      weighbridge: true,
      containerType: ['shipping_container', 'walking_floor'],
      acceptedMaterials: ['abs', 'bopp', 'eps', 'k_resin', 'fire', 'water', 'land'],
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-05-08T01:51:34.039Z',
      updatedAt: '2025-06-13T03:40:52.395Z',
      companyId: 28,
      companyLocationDocuments: [
        {
          id: 14,
          uploadedByUserId: 45,
          reviewedByUserId: null,
          documentType: 'waste_carrier_license',
          documentName: 'Hero-Banner-Placeholder-Dark-1024x480.png',
          documentUrl:
            'https://wastetrade-resources-dev.s3.eu-west-2.amazonaws.com/1749773902379_Hero-Banner-Placeholder-Dark-1024x480.png',
          status: 'pending',
          rejectionReason: null,
          reviewedAt: null,
          expiryDate: null,
          createdAt: '2025-06-13T00:18:22.751Z',
          updatedAt: '2025-06-13T03:40:52.409Z',
          companyLocationId: 1,
        },
      ],
    },
    {
      id: 2,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '123 Green St, Unit 1',
      street: 'street',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'GB',
      stateProvince: 'England',
      officeOpenTime: '01:00:00',
      officeCloseTime: '10:00:00',
      loadingRamp: true,
      weighbridge: true,
      containerType: ['tipperTrucks', 'curtain_slider_standard'],
      acceptedMaterials: null,
      selfLoadUnLoadCapability: true,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-05-08T02:02:13.610Z',
      updatedAt: '2025-06-12T07:10:04.156Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 8,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: null,
      street: null,
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'AI',
      stateProvince: 'England',
      officeOpenTime: '01:30:00',
      officeCloseTime: '10:00:00',
      loadingRamp: true,
      weighbridge: true,
      containerType: ['curtain_slider_standard'],
      acceptedMaterials: null,
      selfLoadUnLoadCapability: true,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-05-16T01:28:56.012Z',
      updatedAt: '2025-05-16T01:28:56.012Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 11,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: null,
      street: null,
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'GB',
      stateProvince: 'England',
      officeOpenTime: '01:30:00',
      officeCloseTime: '10:30:00',
      loadingRamp: true,
      weighbridge: true,
      containerType: ['curtain_slider_standard'],
      acceptedMaterials: null,
      selfLoadUnLoadCapability: true,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-05-20T06:30:50.170Z',
      updatedAt: '2025-05-20T06:30:50.170Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 13,
      locationName: 'Main Warehouse',
      prefix: 'mrs',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: null,
      street: null,
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'GB',
      stateProvince: 'England',
      officeOpenTime: '01:00:00',
      officeCloseTime: '10:30:00',
      loadingRamp: true,
      weighbridge: true,
      containerType: ['tipperTrucks'],
      acceptedMaterials: null,
      selfLoadUnLoadCapability: true,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-01T03:15:46.212Z',
      updatedAt: '2025-06-01T03:15:46.212Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 24,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '123 Green St, Unit 1',
      street: 'street',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'AL',
      stateProvince: 'England',
      officeOpenTime: '09:00:00',
      officeCloseTime: '18:00:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container', 'curtain_slider_standard', 'tipperTrucks'],
      acceptedMaterials: null,
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-12T08:21:38.058Z',
      updatedAt: '2025-06-12T08:23:58.934Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 25,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '123 Green St, Unit 1',
      street: 'street',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'AD',
      stateProvince: 'England',
      officeOpenTime: '06:30:00',
      officeCloseTime: '20:00:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container'],
      acceptedMaterials: null,
      selfLoadUnLoadCapability: true,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-12T08:25:36.360Z',
      updatedAt: '2025-06-12T12:48:41.016Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 33,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '123 Green St, Unit 1',
      street: 'street',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'AQ',
      stateProvince: 'England',
      officeOpenTime: '02:12:00',
      officeCloseTime: '13:17:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container'],
      acceptedMaterials: null,
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-12T12:55:19.002Z',
      updatedAt: '2025-06-12T12:55:19.002Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 34,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '23 Green St, Unit 1',
      street: '23 Green St, Unit 1',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'AD',
      stateProvince: 'England',
      officeOpenTime: '01:11:00',
      officeCloseTime: '21:00:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container'],
      acceptedMaterials: null,
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-12T12:59:46.937Z',
      updatedAt: '2025-06-12T12:59:46.937Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 38,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '5 Elm Grove',
      street: '5 Elm Grove',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'AS',
      stateProvince: 'England',
      officeOpenTime: '01:25:00',
      officeCloseTime: '20:10:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container', 'tipperTrucks', 'curtain_slider_standard'],
      acceptedMaterials: null,
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-12T13:27:25.838Z',
      updatedAt: '2025-06-12T13:27:25.838Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 39,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '123 Green St, Unit 1',
      street: '123 Green St, Unit 1',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'AS',
      stateProvince: 'England',
      officeOpenTime: '04:00:00',
      officeCloseTime: '17:00:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container'],
      acceptedMaterials: null,
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-12T15:23:51.668Z',
      updatedAt: '2025-06-12T15:23:51.668Z',
      companyId: 28,
      companyLocationDocuments: [
        {
          id: 11,
          uploadedByUserId: 45,
          reviewedByUserId: null,
          documentType: 'waste_carrier_license',
          documentName: 'Hero-Banner-Placeholder-Dark-1024x480.png',
          documentUrl:
            'https://wastetrade-resources-dev.s3.eu-west-2.amazonaws.com/1749741830904_Hero-Banner-Placeholder-Dark-1024x480.png',
          status: 'pending',
          rejectionReason: null,
          reviewedAt: null,
          expiryDate: null,
          createdAt: '2025-06-12T15:23:51.685Z',
          updatedAt: '2025-06-12T15:23:51.686Z',
          companyLocationId: 39,
        },
      ],
    },
    {
      id: 40,
      locationName: 'East Dock Depot',
      prefix: 'ms',
      firstName: 'Emily',
      lastName: 'Smith',
      positionInCompany: 'Operations Lead',
      phoneNumber: '+44  2079460821',
      addressLine: 'Unit 5, Riverside Business Park',
      street: 'Mill Road',
      postcode: 'E14 9GH',
      city: 'London',
      country: 'GB',
      stateProvince: 'Greater London',
      officeOpenTime: '07:30:00',
      officeCloseTime: '18:00:00',
      loadingRamp: false,
      weighbridge: true,
      containerType: ['shipping_container', 'walking_floor'],
      acceptedMaterials: ['abs', 'evoh', 'k_resin', 'mdpe', 'pa', 'ldpe'],
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'Driver ID badge required at gate',
      siteSpecificInstructions: 'Please report to security hut on arrival',
      createdAt: '2025-06-13T01:22:31.532Z',
      updatedAt: '2025-06-13T01:22:31.532Z',
      companyId: 28,
      companyLocationDocuments: [
        {
          id: 16,
          uploadedByUserId: 45,
          reviewedByUserId: null,
          documentType: 'waste_carrier_license',
          documentName: 'sample2.pdf',
          documentUrl: 'https://wastetrade-resources-dev.s3.eu-west-2.amazonaws.com/1749777750742_sample2.pdf',
          status: 'pending',
          rejectionReason: null,
          reviewedAt: null,
          expiryDate: null,
          createdAt: '2025-06-13T01:22:31.556Z',
          updatedAt: '2025-06-13T01:22:31.556Z',
          companyLocationId: 40,
        },
      ],
    },
    {
      id: 41,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '123 Green St, Unit 1',
      street: 'street',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'BN',
      stateProvince: 'England',
      officeOpenTime: '07:30:00',
      officeCloseTime: '18:00:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container', 'tipperTrucks'],
      acceptedMaterials: [
        'abs',
        'bopp',
        'eps',
        'eva',
        'evoh',
        'hdpe',
        'hdpe_pp',
        'k_resin',
        'ldpe',
        'lldpe',
        'mdpe',
        'pa',
        'pbt',
        'pc',
        'pc_abs',
        'pe',
        'pe_pa',
        'pe_pet',
        'pe_pp',
        'pet',
        'pet_pvc',
        'pmma',
        'pom',
        'pp',
        'pp_pet',
        'pp_ps',
        'ps',
        'pvc',
        'san',
        'silicone',
        'tpo',
        'tpu',
        'black_casings',
        'creme_casings',
        'fridge',
        'mixed_casings',
        'mixed_weee',
        'bumpers',
        'mixed_bottles',
        'mixed_film',
        'mixed_hangers',
        'mixed_plastic',
        'mixed_rigids',
        'mixed_strapping',
        'ff',
        'n2',
        'oa',
        'osb',
        'osoa',
        'tcans',
        'acans',
        'aluminium',
        'brass',
        'braziery_copper',
        'copper',
        'stainless_steel_304',
        'stainless_steel_316',
        'medium_printed_multi_printing',
        'mixed_white_heavily_printed_multiply_board',
        'multi_printing',
        'special_wood_free_binders',
        'unprinted_bleached_sulphate_board',
        'unprinted_tissue_coloured_in_the_mass',
        'white_coated_woodfree_paper',
        'white_envelope_cuttings',
        'white_heavily_printed_multiply_board',
        'white_lightly_printed_multi_ply_board',
        'white_mechanical_pulp_based_coated_and_uncoated_paper',
        'white_mechanical_pulp_based_paper_containing_coated_paper',
        'white_shavings',
        'white_unprinted_multi_ply_board',
        'white_unprinted_tissue',
        'white_wood_free_uncoated_shavings',
        'white_woodfree_letters',
        'white_woodfree_letters_unprinted',
        'white_woodfree_papers',
        'white_woodfree_shavings',
        'woodfree_binders',
        'new_shavings_of_corrugated_board',
        'unused_corrugated_kraft',
        'unused_corrugated_material',
        'used_corrugated_kraft_1',
        'used_kraft',
        'coloured_log_end_tissue',
        'heavily_printed_white_shavings',
        'heavily_printed_white_shavings_without_glue',
        'lightly_printed_white_shavings',
        'lightly_printed_white_shavings_without_glue',
        'multigrade',
        'newspapers',
        'ordinary_sorted_colored_letters',
        'ordinary_sorted_office_paper',
        'sorted_coloured_letters',
        'unsold_newspapers',
        'unsold_newspapers_not_intended_for_deinking',
        'white_log_end_tissue',
        'white_mechanical_pulp_based_bookquire',
        'white_woodfree_bookquire',
        'blister_pack',
        'carbonless_copy_paper',
        'cores',
        'dry_labels',
        'labels_with_base_layer',
        'mixed_envelopes',
        'mixed_packaging',
        'mixed_papers',
        'printed_white_and_colored_wet_strength_woodfree_papers',
        'printed_white_envelope',
        'printed_white_wet_strength_woodfree_papers',
        'unprinted_white_and_colored_wet_strength_papers',
        'unprinted_white_wet_strength_woodfree_papers_unprinted_white_wets',
        'unused_kraft_sacks',
        'unused_kraft_sacks_with_plastic_layer_papers_and_poly_liners',
        'unused_liquid_packaging_board',
        'unused_paper_cups_and_other_tableware',
        'used_kraft_sacks',
        'used_kraft_sacks_with_plastic_layer_papers',
        'used_liquid_packaging_board',
        'used_paper_cups_and_other_used_tableware',
        'wet_labels',
        'corrugated_board',
        'corrugated_paper_and_board',
        'corrugated_paper_and_board_packaging',
        'grey_board',
        'magazines',
        'magazines_with_product_samples',
        'magazines_without_glue',
        'mixed_magazines_and_newspapers',
        'mixed_newspapers_and_magazines_1',
        'mixed_papers_and_boards_sorted',
        'newspapers_and_magazines',
        'ordinary_corrugated_board',
        'ordinary_corrugated_paper_and_board',
        'sorted_graphic_paper_for_deinking',
        'natural_rubber',
        'chloroprene_rubber_CR',
        'elastomers',
        'ethylene_propylene_diene_monomer_epdm',
        'latex_products',
        'nitrile_rubber_nbr',
        'polybutadiene_rubber_BR',
        'polyurethane_rubber_PU',
        'recycled_rubber_products',
        'rubber_compounds',
        'rubber_conveyor_belts',
        'rubber_footwear',
        'rubber_hoses_and_tubing',
        'rubber_manufacturing_waste',
        'rubber_playground_surfaces',
        'rubber_seals_and_gaskets',
        'styrene_butadiene_rubber',
      ],
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-13T01:28:50.799Z',
      updatedAt: '2025-06-13T01:28:50.799Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 42,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '123 Green St, Unit 1',
      street: 'street',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'BN',
      stateProvince: 'England',
      officeOpenTime: '07:30:00',
      officeCloseTime: '18:00:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container', 'tipperTrucks'],
      acceptedMaterials: [
        'abs',
        'bopp',
        'eps',
        'eva',
        'evoh',
        'hdpe',
        'hdpe_pp',
        'k_resin',
        'ldpe',
        'lldpe',
        'mdpe',
        'pa',
        'pbt',
        'pc',
        'pc_abs',
        'pe',
        'pe_pa',
        'pe_pet',
        'pe_pp',
        'pet',
        'pet_pvc',
        'pmma',
        'pom',
        'pp',
        'pp_pet',
        'pp_ps',
        'ps',
        'pvc',
        'san',
        'silicone',
        'tpo',
        'tpu',
        'black_casings',
        'creme_casings',
        'fridge',
        'mixed_casings',
        'mixed_weee',
        'bumpers',
        'mixed_bottles',
        'mixed_film',
        'mixed_hangers',
        'mixed_plastic',
        'mixed_rigids',
        'mixed_strapping',
        'ff',
        'n2',
        'oa',
        'osb',
        'osoa',
        'tcans',
        'acans',
        'aluminium',
        'brass',
        'braziery_copper',
        'copper',
        'stainless_steel_304',
        'stainless_steel_316',
        'medium_printed_multi_printing',
        'mixed_white_heavily_printed_multiply_board',
        'multi_printing',
        'special_wood_free_binders',
        'unprinted_bleached_sulphate_board',
        'unprinted_tissue_coloured_in_the_mass',
        'white_coated_woodfree_paper',
        'white_envelope_cuttings',
        'white_heavily_printed_multiply_board',
        'white_lightly_printed_multi_ply_board',
        'white_mechanical_pulp_based_coated_and_uncoated_paper',
        'white_mechanical_pulp_based_paper_containing_coated_paper',
        'white_shavings',
        'white_unprinted_multi_ply_board',
        'white_unprinted_tissue',
        'white_wood_free_uncoated_shavings',
        'white_woodfree_letters',
        'white_woodfree_letters_unprinted',
        'white_woodfree_papers',
        'white_woodfree_shavings',
        'woodfree_binders',
        'new_shavings_of_corrugated_board',
        'unused_corrugated_kraft',
        'unused_corrugated_material',
        'used_corrugated_kraft_1',
        'used_kraft',
        'coloured_log_end_tissue',
        'heavily_printed_white_shavings',
        'heavily_printed_white_shavings_without_glue',
        'lightly_printed_white_shavings',
        'lightly_printed_white_shavings_without_glue',
        'multigrade',
        'newspapers',
        'ordinary_sorted_colored_letters',
        'ordinary_sorted_office_paper',
        'sorted_coloured_letters',
        'unsold_newspapers',
        'unsold_newspapers_not_intended_for_deinking',
        'white_log_end_tissue',
        'white_mechanical_pulp_based_bookquire',
        'white_woodfree_bookquire',
        'blister_pack',
        'carbonless_copy_paper',
        'cores',
        'dry_labels',
        'labels_with_base_layer',
        'mixed_envelopes',
        'mixed_packaging',
        'mixed_papers',
        'printed_white_and_colored_wet_strength_woodfree_papers',
        'printed_white_envelope',
        'printed_white_wet_strength_woodfree_papers',
        'unprinted_white_and_colored_wet_strength_papers',
        'unprinted_white_wet_strength_woodfree_papers_unprinted_white_wets',
        'unused_kraft_sacks',
        'unused_kraft_sacks_with_plastic_layer_papers_and_poly_liners',
        'unused_liquid_packaging_board',
        'unused_paper_cups_and_other_tableware',
        'used_kraft_sacks',
        'used_kraft_sacks_with_plastic_layer_papers',
        'used_liquid_packaging_board',
        'used_paper_cups_and_other_used_tableware',
        'wet_labels',
        'corrugated_board',
        'corrugated_paper_and_board',
        'corrugated_paper_and_board_packaging',
        'grey_board',
        'magazines',
        'magazines_with_product_samples',
        'magazines_without_glue',
        'mixed_magazines_and_newspapers',
        'mixed_newspapers_and_magazines_1',
        'mixed_papers_and_boards_sorted',
        'newspapers_and_magazines',
        'ordinary_corrugated_board',
        'ordinary_corrugated_paper_and_board',
        'sorted_graphic_paper_for_deinking',
        'natural_rubber',
        'chloroprene_rubber_CR',
        'elastomers',
        'ethylene_propylene_diene_monomer_epdm',
        'latex_products',
        'nitrile_rubber_nbr',
        'polybutadiene_rubber_BR',
        'polyurethane_rubber_PU',
        'recycled_rubber_products',
        'rubber_compounds',
        'rubber_conveyor_belts',
        'rubber_footwear',
        'rubber_hoses_and_tubing',
        'rubber_manufacturing_waste',
        'rubber_playground_surfaces',
        'rubber_seals_and_gaskets',
        'styrene_butadiene_rubber',
      ],
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-13T01:30:25.700Z',
      updatedAt: '2025-06-13T01:30:25.700Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 43,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '123 Green St, Unit 1',
      street: 'street',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'DZ',
      stateProvince: 'England',
      officeOpenTime: '06:00:00',
      officeCloseTime: '20:00:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['curtain_slider_standard', 'shipping_container', 'walking_floor', 'tipperTrucks'],
      acceptedMaterials: ['evoh', 'k_resin', 'mdpe'],
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-13T01:48:06.254Z',
      updatedAt: '2025-06-13T01:48:06.254Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 44,
      locationName: 'Northside Distribution Center',
      prefix: 'mr',
      firstName: 'Olivia',
      lastName: 'Brown',
      positionInCompany: 'Site Supervisor',
      phoneNumber: '+44  1612345678',
      addressLine: 'Building A, Tech Park',
      street: 'Innovation Drive',
      postcode: 'M50 2LW',
      city: 'Manchester',
      country: 'AD',
      stateProvince: 'Greater Manchester',
      officeOpenTime: '06:45:00',
      officeCloseTime: '16:30:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container', 'tipperTrucks'],
      acceptedMaterials: ['chloroprene_rubber_CR'],
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'Site induction required',
      siteSpecificInstructions: 'Wear high-vis vest and hard hat at all times',
      createdAt: '2025-06-13T01:50:48.907Z',
      updatedAt: '2025-06-13T01:50:48.907Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 45,
      locationName: 'Northside Distribution Center',
      prefix: 'mr',
      firstName: 'Olivia',
      lastName: 'Brown',
      positionInCompany: 'Site Supervisor',
      phoneNumber: '+44  123456789',
      addressLine: 'Building A, Tech Park',
      street: 'Innovation Drive',
      postcode: 'M50 2LW',
      city: 'Manchester',
      country: 'DZ',
      stateProvince: 'Manchester',
      officeOpenTime: '01:30:00',
      officeCloseTime: '23:00:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container'],
      acceptedMaterials: ['abs'],
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-13T01:52:44.750Z',
      updatedAt: '2025-06-13T01:52:44.750Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
    {
      id: 46,
      locationName: 'Northside Distribution Center',
      prefix: 'mr',
      firstName: 'Olivia',
      lastName: 'Brown',
      positionInCompany: 'Site Supervisor',
      phoneNumber: '+44  123456789',
      addressLine: 'Building A, Tech Park',
      street: 'street',
      postcode: 'M50 2LW',
      city: 'Manchester',
      country: 'AD',
      stateProvince: 'Greater Manchester',
      officeOpenTime: '01:00:00',
      officeCloseTime: '12:00:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container'],
      acceptedMaterials: ['abs', 'eva'],
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-13T02:00:13.059Z',
      updatedAt: '2025-06-13T02:00:32.155Z',
      companyId: 28,
      companyLocationDocuments: [
        {
          id: 17,
          uploadedByUserId: 45,
          reviewedByUserId: null,
          documentType: 'waste_carrier_license',
          documentName: 'Hero-Banner-Placeholder-Dark-1024x480.png',
          documentUrl:
            'https://wastetrade-resources-dev.s3.eu-west-2.amazonaws.com/1749780031506_Hero-Banner-Placeholder-Dark-1024x480.png',
          status: 'pending',
          rejectionReason: null,
          reviewedAt: null,
          expiryDate: null,
          createdAt: '2025-06-13T02:00:32.168Z',
          updatedAt: '2025-06-13T02:00:32.168Z',
          companyLocationId: 46,
        },
      ],
    },
    {
      id: 47,
      locationName: 'Main Warehouse',
      prefix: 'mr',
      firstName: 'John',
      lastName: 'Doe',
      positionInCompany: 'Manager',
      phoneNumber: '+44  1234567890',
      addressLine: '123 Green St, Unit 1',
      street: 'street',
      postcode: 'AB1 2CD',
      city: 'London',
      country: 'AL',
      stateProvince: 'England',
      officeOpenTime: '01:00:00',
      officeCloseTime: '12:00:00',
      loadingRamp: false,
      weighbridge: false,
      containerType: ['shipping_container'],
      acceptedMaterials: ['chloroprene_rubber_CR'],
      selfLoadUnLoadCapability: false,
      accessRestrictions: 'N/a',
      siteSpecificInstructions: null,
      createdAt: '2025-06-13T02:44:05.920Z',
      updatedAt: '2025-06-13T02:44:05.920Z',
      companyId: 28,
      companyLocationDocuments: [],
    },
  ] as any);
  mapCountryCodeToName = mapCountryCodeToName;

  getLocationAddress = getLocationAddress;
}
