services:

  frontend:
    build:
      context: .
      args:
        API_URL: ${API_URL}
    restart: always
    container_name: frontend
    networks:
      - frontend
        #env_file:
        #- .env
    ports:
      - '8080:80'
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  frontend:
    driver: bridge
