export const colour = [
  'Black',
  'Blue',
  'Brown',
  'Coloured/jazz',
  'Green',
  'Grey',
  'Natural',
  'Red',
  'White',
];

export const finishing = [
  'Baled',
  'Blocks',
  'Flakes',
  'Lumps',
  'Masterbatch',
  'Pieces',
  'Powder',
  'Regrind',
  'Resin',
  'Rolls',
  'Sheets',
  'Shred',
];

export const packing = [
  'Bags',
  'Bales',
  'Boxes',
  'Bulk Bags',
  'Loose',
  'Octabins/Gaylords',
  'Pallets',
];

export const plasticForm = [
  'Airbags',
  'Bags',
  'Bins',
  'Blister',
  'Bottles',
  'Buckets',
  'Bumpers',
  'Cable/s',
  'Cans',
  'Caps',
  'Casings',
  'Cores',
  'Corex',
  'Crates',
  'Cups',
  'Discs',
  'Door Skins',
  'Drip Tape',
  'Film',
  'Filters',
  'Fines',
  'Fishing Line',
  'Hangers',
  'Keyboard',
  'Modem',
  'Moulds',
  'Nets',
  'Pipes',
  'Pots',
  'Preforms',
  'Printer',
  'Profiles',
  'Reels',
  'Rigid',
  'Runners',
  'Skeletons',
  'Soft',
  'Sprues',
  'Strapping',
  'String',
  'Tool',
  'Trays',
  'Tubes',
  'Vacuum',
];

export const plasticGrading = [
  '6',
  '12',
  '46',
  '66',
  '100',
  '612',
  '*1-7',
  '*3-7',
  'Jun-66',
  '50/50',
  '60/40',
  '70/30',
  '75/25',
  '80/20',
  '85/15',
  '90/10',
  '95/5',
  '98/2',
  '99/1',
  'A Grade',
  'Agricultural',
  'Aluminium',
  'Automotive',
  'B Grade',
  'C Grade',
  'CD',
  'CD/DVD',
  'Coated',
  'Computer',
  'Construction',
  'DVD',
  'Electrical',
  'Fish Box',
  'Floor Sweeps',
  'Fridge',
  'G',
  'GF',
  'GF10',
  'GF15',
  'GF20',
  'GF25',
  'GF30',
  'GF35',
  'GF40',
  'GF50',
  'LCD',
  'Metalised',
  'Mixed',
  'Non-Woven',
  'Offcuts',
  'Printed',
  'Production Waste',
  'Supermarket',
  'Technical',
  'TV',
  'Tyvek',
  'Uncoated',
  'Walmart',
  'Washing Machine',
  'Wet',
  'Woven',
  'Laminates',
];

export const fibreGrading = ['High', 'Kraft', 'Medium', 'Ordinary', 'Special'];

export const materialTypes = [
  {
    name: 'Plastic',
    code: 'plastic',
    materials: [
      'ABS',
      'BOPP',
      'EPS',
      'EVA',
      'EVOH',
      'HDPE',
      'HDPE/PP',
      'K-Resin',
      'LDPE',
      'LLDPE',
      'MDPE',
      'PA',
      'PBT',
      'PC',
      'PC/ABS',
      'PE',
      'PE/PA',
      'PE/PET',
      'PE/PP',
      'PET',
      'PET/PVC',
      'PMMA',
      'POM',
      'PP',
      'PP/PET',
      'PP/PS',
      'PS',
      'PVC',
      'SAN',
      'Silicone',
      'TPO',
      'TPU',
      'Black Casings',
      'Crème Casings',
      'Fridge',
      'Mixed Casings',
      'Mixed WEEE',
      'Bumpers',
      'Mixed Bottles',
      'Mixed Film',
      'Mixed Hangers',
      'Mixed Plastic',
      'Mixed Rigids',
      'Mixed Strapping',
    ],
    form: plasticForm,
    grading: plasticGrading,
    colour: colour,
    finishing: finishing,
    packing: packing,
  },
  {
    name: 'EFW',
    code: 'efw',
    materials: [],
    form: [],
    grading: [],
    colour: colour,
    finishing: finishing,
    packing: packing,
  },
  {
    name: 'Metals',
    code: 'metals',
    materials: [
      'FF',
      'N2',
      'OA',
      'OSB',
      'OSOA',
      'TCANS',
      'ACANS',
      'Alumnium',
      'Brass',
      'Braziery Copper',
      'Copper',
      'Stainless Steel 304',
      'Stainless Steel 316',
    ],
    form: [],
    grading: [],
    colour: colour,
    finishing: finishing,
    packing: packing,
  },
  {
    name: 'Fibre',
    code: 'fibre',
    materials: [
      'Medium printed multi printing',
      'Mixed white heavily printed multiply board',
      'Multi printing',
      'Special wood free binders',
      'Unprinted bleached sulphate board',
      'Unprinted tissue coloured in the mass',
      'White coated woodfree paper',
      'White envelope cuttings',
      'White heavily printed multiply board',
      'White lightly printed multi-ply board',
      'White mechanical pulp-based coated and uncoated paper',
      'White mechanical pulp-based paper containing coated paper',
      'White shavings',
      'White unprinted multi-ply board',
      'White unprinted tissue',
      'White wood free uncoated shavings',
      'White woodfree letters',
      'White woodfree letters unprinted',
      'White woodfree papers',
      'White woodfree shavings',
      'Woodfree binders',
      'New shavings of corrugated board',
      'Unused corrugated kraft',
      'Unused corrugated material',
      'Used corrugated kraft 1',
      'Used kraft',
      'Colored log end tissue',
      'Colored woodfree magazines',
      'Heavily printed white shavings',
      'Heavily printed white shavings without glue',
      'Lightly printed white shavings',
      'Lightly printed white shavings without glue',
      'Multigrade',
      'Newspapers',
      'Ordinary sorted colored letters',
      'Ordinary sorted office paper',
      'Sorted coloured letters',
      'Unsold newspapers',
      'Unsold newspapers not intended for deinking',
      'White log end tissue',
      'White mechanical pulp-based bookquire',
      'White woodfree bookquire',
      'Blister pack',
      'Carbonless copy paper (Ncr)',
      'Cores',
      'Dry labels',
      'Labels with base layer',
      'Mixed envelopes',
      'Mixed packaging',
      'Mixed papers',
      'Paper release liner for self-adhesive labels',
      'Printed white and coloured wetstrength woodfree papers',
      'Printed White Envelope',
      'Printed White Wet-Strength Woodfree Papers',
      'Unprinted White And Colored Wet-Strength Papers',
      'Unprinted White Wet-Strength Woodfree Papers',
      'Unprinted White Wets',
      'Unused Kraft Sacks',
      'Unused Kraft Sacks With Plastic Layer Papers And Poly Liners',
      'Unused Liquid Packaging Board',
      'Unused Paper Cups And Other Tableware',
      'Used Kraft Sacks',
      'Used Kraft Sacks With Plastic Layer Papers',
      'Used Liquid Packaging Board',
      'Used Paper Cups And Other Used Tableware',
      'Wet Labels',
      'Corrugated board',
      'Corrugated paper and board',
      'Corrugated paper and board packaging',
      'Grey board',
      'Magazines',
      'Magazines with product samples',
      'Magazines without glue',
      'Mixed magazines and newspapers',
      'Mixed newspapers & magazines 1',
      'Mixed papers and boards (sorted)',
      'Newspapers and magazines',
      'Ordinary corrugated board',
      'Ordinary corrugated paper and board',
      'Sorted graphic paper for deinking',
    ],
    form: [],
    grading: fibreGrading,
    colour: colour,
    finishing: finishing,
    packing: packing,
  },
  {
    name: 'Rubber',
    code: 'rubber',
    materials: [
      'Natural rubber',
      'Chloroprene Rubber (CR)',
      'Elastomers',
      'Ethylene-Propylene-Diene Monomer (EPDM)',
      'Latex Products',
      'Nitrile Rubber (NBR)',
      'Polybutadiene Rubber (BR)',
      'Polyurethane Rubber (PU)',
      'Recycled Rubber Products',
      'Rubber Compounds',
      'Rubber Conveyor Belts',
      'Rubber Footwear',
      'Rubber Hoses and Tubing',
      'Rubber Manufacturing Waste',
      'Rubber Playground Surfaces',
      'Rubber Seals and Gaskets',
      'Styrene-Butadiene Rubber (SBR)',
    ],
    form: [],
    grading: [],
    colour: colour,
    finishing: finishing,
    packing: packing,
  },
];
