export const MAP_MATERIAL_TYPE_TO_ITEM = {
  plastic: [
    { name: 'ABS', code: 'ABS' },
    { name: 'BOPP', code: 'BOPP' },
    { name: 'EPS', code: 'EPS' },
    { name: 'EVA', code: 'EVA' },
    { name: 'EVOH', code: 'EVOH' },
    { name: 'HDPE', code: 'HDPE' },
    { name: 'HDPE/PP', code: 'HDPE/PP' },
    { name: 'K-Resin', code: 'K-Resin' },
    { name: 'LDPE', code: 'LDPE' },
    { name: 'LLDPE', code: 'LLDPE' },
    { name: 'MDPE', code: 'MDPE' },
    { name: 'PA', code: 'PA' },
    { name: 'PBT', code: 'PBT' },
    { name: 'PC', code: 'PC' },
    { name: 'PC/ABS', code: 'PC/ABS' },
    { name: 'PE', code: 'PE' },
    { name: 'PE/PA', code: 'PE/PA' },
    { name: 'PE/PET', code: 'PE/PET' },
    { name: 'PE/PP', code: 'PE/PP' },
    { name: 'PET', code: 'PET' },
    { name: 'PET/PVC', code: 'PET/PVC' },
    { name: 'PMMA', code: 'PMMA' },
    { name: 'POM', code: 'POM' },
    { name: 'PP', code: 'PP' },
    { name: 'PP/PET', code: 'PP/PET' },
    { name: 'PP/PS', code: 'PP/PS' },
    { name: 'PS', code: 'PS' },
    { name: 'PVC', code: 'PVC' },
    { name: 'SAN', code: 'SAN' },
    { name: 'Silicone', code: 'Silicone' },
    { name: 'TPO', code: 'TPO' },
    { name: 'TPU', code: 'TPU' },
    { name: 'Black Casings', code: 'Black Casings' },
    { name: 'Crème Casings', code: 'Crème Casings' },
    { name: 'Fridge', code: 'Fridge' },
    { name: 'Mixed Casings', code: 'Mixed Casings' },
    { name: 'Mixed WEEE', code: 'Mixed WEEE' },
    { name: 'Bumpers', code: 'Bumpers' },
    { name: 'Mixed Bottles', code: 'Mixed Bottles' },
    { name: 'Mixed Film', code: 'Mixed Film' },
    { name: 'Mixed Hangers', code: 'Mixed Hangers' },
    { name: 'Mixed Plastic', code: 'Mixed Plastic' },
    { name: 'Mixed Rigids', code: 'Mixed Rigids' },
    { name: 'Mixed Strapping', code: 'Mixed Strapping' },
  ],
  efw: [],
  metals: [
    { name: 'FF', code: 'FF' },
    { name: 'N2', code: 'N2' },
    { name: 'OA', code: 'OA' },
    { name: 'OSB', code: 'OSB' },
    { name: 'OSOA', code: 'OSOA' },
    { name: 'TCANS', code: 'TCANS' },
    { name: 'ACANS', code: 'ACANS' },
    { name: 'Alumnium', code: 'Alumnium' },
    { name: 'Brass', code: 'Brass' },
    { name: 'Braziery Copper', code: 'Braziery Copper' },
    { name: 'Copper', code: 'Copper' },
    { name: 'Stainless Steel 304', code: 'Stainless Steel 304' },
    { name: 'Stainless Steel 316', code: 'Stainless Steel 316' },
  ],
  fibre: [
    { name: 'Medium printed multi printing', code: 'Medium printed multi printing' },
    { name: 'Mixed white heavily printed multiply board, ', code: 'Mixed white heavily printed multiply board, ' },
    { name: 'Multi printing', code: 'Multi printing' },
    { name: 'Special wood free binders', code: 'Special wood free binders' },
    { name: 'Unprinted bleached sulphate board', code: 'Unprinted bleached sulphate board' },
    { name: 'Unprinted tissue coloured in the mass', code: 'Unprinted tissue coloured in the mass' },
    { name: 'White coated woodfree paper', code: 'White coated woodfree paper' },
    { name: 'White envelope cuttings', code: 'White envelope cuttings' },
    { name: 'White heavily printed multiply board', code: 'White heavily printed multiply board' },
    { name: 'White lightly printed multi-ply board', code: 'White lightly printed multi-ply board' },
    {
      name: 'White mechanical pulp-based coated and uncoated paper',
      code: 'White mechanical pulp-based coated and uncoated paper',
    },
    {
      name: 'White mechanical pulp-based paper containing coated paper',
      code: 'White mechanical pulp-based paper containing coated paper',
    },
    { name: 'White shavings', code: 'White shavings' },
    { name: 'White unprinted multi-ply board', code: 'White unprinted multi-ply board' },
    { name: 'White unprinted tissue', code: 'White unprinted tissue' },
    { name: 'White wood free uncoated shavings', code: 'White wood free uncoated shavings' },
    { name: 'White woodfree letters', code: 'White woodfree letters' },
    { name: 'White woodfree letters unprinted', code: 'White woodfree letters unprinted' },
    { name: 'White woodfree papers', code: 'White woodfree papers' },
    { name: 'White woodfree shavings', code: 'White woodfree shavings' },
    { name: 'Woodfree binders', code: 'Woodfree binders' },
    { name: 'New shavings of corrugated board', code: 'New shavings of corrugated board' },
    { name: 'Unused corrugated kraft', code: 'Unused corrugated kraft' },
    { name: 'Unused corrugated material', code: 'Unused corrugated material' },
    { name: 'Used corrugated kraft 1', code: 'Used corrugated kraft 1' },
    { name: 'Used kraft', code: 'Used kraft' },
    { name: 'Colored log end tissue', code: 'Colored log end tissue' },
    { name: 'Colored woodfree magazines', code: 'Colored woodfree magazines' },
    { name: 'Heavily printed white shavings', code: 'Heavily printed white shavings' },
    { name: 'Heavily printed white shavings without glue', code: 'Heavily printed white shavings without glue' },
    { name: 'Lightly printed white shavings', code: 'Lightly printed white shavings' },
    { name: 'Lightly printed white shavings without glue', code: 'Lightly printed white shavings without glue' },
    { name: 'Multigrade', code: 'Multigrade' },
    { name: 'Newspapers', code: 'Newspapers' },
    { name: 'Ordinary sorted colored letters', code: 'Ordinary sorted colored letters' },
    { name: 'Ordinary sorted office paper', code: 'Ordinary sorted office paper' },
    { name: 'Sorted coloured letters', code: 'Sorted coloured letters' },
    { name: 'Unsold newspapers', code: 'Unsold newspapers' },
    { name: 'Unsold newspapers not intended for deinking', code: 'Unsold newspapers not intended for deinking' },
    { name: 'White log end tissue', code: 'White log end tissue' },
    { name: 'White mechanical pulp-based bookquire', code: 'White mechanical pulp-based bookquire' },
    { name: 'White woodfree bookquire', code: 'White woodfree bookquire' },
    { name: 'Blister pack', code: 'Blister pack' },
    { name: 'Carbonless copy aper (Ncr)', code: 'Carbonless copy aper (Ncr' },
    { name: 'Cores', code: 'Cores' },
    { name: 'Dry labels', code: 'Dry labels' },
    { name: 'Labels with base Llyer', code: 'Labels with base Llyer' },
    { name: 'Mixed envelopes', code: 'Mixed envelopes' },
    { name: 'Mixed packaging', code: 'Mixed packaging' },
    { name: 'Mixed papers', code: 'Mixed papers' },
    { name: 'Paper release liner for self- adhesive labels', code: 'Paper release liner for self- adhesive labels' },
    {
      name: 'Printed white and coloured wetstrength woodfree papers',
      code: 'Printed white and coloured wetstrength woodfree papers',
    },
    { name: 'Printed White Envelope', code: 'Printed White Envelope' },
    { name: 'Printed White Wet-Strength Woodfree Papers', code: 'Printed White Wet-Strength Woodfree Papers' },
    {
      name: 'Unprinted White And Colored Wet-Strength Papers',
      code: 'Unprinted White And Colored Wet-Strength Papers',
    },
    {
      name: 'Unprinted White Wet-Strength Woodfree Papers Unprinted White Wets',
      code: 'Unprinted White Wet-Strength Woodfree Papers Unprinted White Wets',
    },
    { name: 'Unused Kraft Sacks', code: 'Unused Kraft Sacks' },
    {
      name: 'Unused Kraft Sacks With Plastic Layer Papers And Poly Liners',
      code: 'Unused Kraft Sacks With Plastic Layer Papers And Poly Liners',
    },
    { name: 'Unused Liquid Packaging Board', code: 'Unused Liquid Packaging Board' },
    { name: 'Unused Paper Cups And Other Tableware', code: 'Unused Paper Cups And Other Tableware' },
    { name: 'Used Kraft Sacks', code: 'Used Kraft Sacks' },
    { name: 'Used Kraft Sacks With Plastic Layer Papers', code: 'Used Kraft Sacks With Plastic Layer Papers' },
    { name: 'Used Liquid Packaging Board', code: 'Used Liquid Packaging Board' },
    { name: 'Used Paper Cups And Other Used Tableware', code: 'Used Paper Cups And Other Used Tableware' },
    { name: 'Wet Labels', code: 'Wet Labels' },
    { name: 'Corrugated board', code: 'Corrugated board' },
    { name: 'Corrugated paper and board', code: 'Corrugated paper and board' },
    { name: 'Corrugated paper and board packaging', code: 'Corrugated paper and board packaging' },
    { name: 'Grey board', code: 'Grey board' },
    { name: 'Magazines', code: 'Magazines' },
    { name: 'Magazines with product samples', code: 'Magazines with product samples' },
    { name: 'Magazines without glue', code: 'Magazines without glue' },
    { name: 'Mixed magazines and newspapers', code: 'Mixed magazines and newspapers' },
    { name: 'Mixed newspapers & magazines 1', code: 'Mixed newspapers & magazines 1' },
    { name: 'Mixed papers and boards (sorted)', code: 'Mixed papers and boards (sorted' },
    { name: 'Newspapers and magazines', code: 'Newspapers and magazines' },
    { name: 'Ordinary corrugated board', code: 'Ordinary corrugated board' },
    { name: 'Ordinary corrugated paper and board', code: 'Ordinary corrugated paper and board' },
    { name: 'Sorted graphic paper for deinking', code: 'Sorted graphic paper for deinking' },
  ],
  rubber: [
    { name: 'Natural rubber', code: 'Natural rubber' },
    { name: 'Chloroprene Rubber (CR)', code: 'Chloroprene Rubber (CR' },
    { name: 'Elastomers', code: 'Elastomers' },
    { name: 'Ethylene-Propylene-Diene Monomer (EPDM)', code: 'Ethylene-Propylene-Diene Monomer (EPDM' },
    { name: 'Latex Products', code: 'Latex Products' },
    { name: 'Nitrile Rubber (NBR)', code: 'Nitrile Rubber (NBR' },
    { name: 'Polybutadiene Rubber (BR)', code: 'Polybutadiene Rubber (BR' },
    { name: 'Polyurethane Rubber (PU)', code: 'Polyurethane Rubber (PU' },
    { name: 'Recycled Rubber Products', code: 'Recycled Rubber Products' },
    { name: 'Rubber Compounds', code: 'Rubber Compounds' },
    { name: 'Rubber Conveyor Belts', code: 'Rubber Conveyor Belts' },
    { name: 'Rubber Footwear', code: 'Rubber Footwear' },
    { name: 'Rubber Hoses and Tubing', code: 'Rubber Hoses and Tubing' },
    { name: 'Rubber Manufacturing Waste', code: 'Rubber Manufacturing Waste' },
    { name: 'Rubber Playground Surfaces', code: 'Rubber Playground Surfaces' },
    { name: 'Rubber Seals and Gaskets', code: 'Rubber Seals and Gaskets' },
    { name: 'Styrene-Butadiene Rubber (SBR)', code: 'Styrene-Butadiene Rubber (SBR' },
  ],
};
